/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ContactMeModel.glb 
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, Html } from '@react-three/drei'

const scrollToWelcome = () => {
  const welcomeSection = document.getElementById('welcome');
  if (welcomeSection) {
    welcomeSection.scrollIntoView({ behavior: 'smooth' });
  }
};

const scrollToMyWorks = () => {
  const welcomeSection = document.getElementById('my-works');
  if (welcomeSection) {
    welcomeSection.scrollIntoView({ behavior: 'smooth' });
  }
};

const scrollToAboutMe = () => {
  const welcomeSection = document.getElementById('aboutme');
  if (welcomeSection) {
    welcomeSection.scrollIntoView({ behavior: 'smooth' });
  }
};

export default function Model4(props) {
  const { nodes, materials } = useGLTF('/ContactMeModel.glb')

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.RearCam.geometry} material={materials['Glass.001']} position={[-0.003, 0.018, -0.001]} rotation={[-Math.PI, 0, 0]} scale={0.003} />
      <mesh geometry={nodes.Volume.geometry} material={materials.button} position={[0.272, 0.289, -0.001]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.003} />
      <mesh geometry={nodes.PowerButton.geometry} material={materials.button} position={[0.272, 0.187, -0.001]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.003} />
      <mesh geometry={nodes.FrontCam.geometry} material={materials['Glass.001']} position={[-0.065, 0.592, 0.007]} scale={0.003} />
      <group position={[-0.003, 0.018, -0.001]} rotation={[-Math.PI, 0, 0]} scale={0.003}>
        <mesh geometry={nodes.Mesh016.geometry} material={materials['Mat.1']} />
        <mesh geometry={nodes.Mesh016_1.geometry} material={materials['Mat.2']} />
        <mesh geometry={nodes.Mesh016_2.geometry} material={materials['Mat.3']} />
      </group>
      <group position={[-0.003, 0.018, -0.001]} rotation={[-Math.PI, 0, 0]} scale={0.003}>
        <mesh geometry={nodes.Mesh017.geometry}>
          <meshBasicMaterial>
            <Html distanceToCamera={10} position={[0, 0, 0.001]}>
              {/* Render your HTML content for the phone screen here */}
              <div className='contact-form'>
                <form className='my-form'>
                  <fieldset>
                    <legend>Message me!</legend>

                    <div className="form-group">
                      <label htmlFor="fullname">Fullname</label>
                      <input type='text' id="fullname" name='fullname' required placeholder='Enter your name...' />
                    </div>

                    <div className="form-group form-group-b">
                      <label htmlFor="email">Email</label>
                      <input type='email' id="email" name="email" required placeholder='Enter your email...' />
                    </div>

                    <div className="form-group form-group-b">
                      <label htmlFor="message">Message</label>
                      <textarea id="message" name="message" required placeholder='Your message...' rows="8" className="textarea"></textarea>
                    </div>

                    <button className="my-form-button" type='submit'>Send</button>
                    <div className="result-message">
                      <p>Thank you you for sending me a message!</p>
                    </div>
                  </fieldset>
                  <div className="contact-me-navigation">
                        <p><span onClick={scrollToWelcome}>Home </span>
                            <span onClick={scrollToAboutMe}>| About Me </span>
                            <span onClick={scrollToMyWorks}>| My Works</span>
                        </p>
                  </div>
                </form>
              </div>
            </Html>
          </meshBasicMaterial>
        </mesh>
        <mesh geometry={nodes.Mesh017_1.geometry} material={materials['PhoneScreen.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/ContactMeModel.glb')
